export type VisualBlockKind = "cube" | "sphere" | "cylinder";

export interface VisualBlockTransform {
  translate: [number, number, number];
  rotate: [number, number, number];
}

export interface VisualBlock {
  id: string;
  kind: VisualBlockKind;
  size: [number, number, number];
  radius: number;
  height: number;
  center: boolean;
  transform: VisualBlockTransform;
}

export function createVisualBlock(
  kind: VisualBlockKind,
  id = `${kind}-${Date.now()}`,
): VisualBlock {
  return {
    id,
    kind,
    size: [20, 20, 20],
    radius: 10,
    height: 20,
    center: true,
    transform: { translate: [0, 0, 0], rotate: [0, 0, 0] },
  };
}

export function generateOpenSCADFromBlocks(blocks: readonly VisualBlock[]) {
  const usableBlocks = blocks.filter((block) => block != null);
  if (usableBlocks.length === 0) return "// Add a block to begin\n";

  const body = usableBlocks.map((block) => generateBlock(block)).join("\n\n");
  return `// Generated by ISE Studio visual blocks\nunion() {\n${indent(body)}\n}\n`;
}

function generateBlock(block: VisualBlock) {
  const { translate, rotate } = block.transform;
  const transforms = [
    `translate([${formatVector(translate)}])`,
    `rotate([${formatVector(rotate)}])`,
  ];
  const primitive = generatePrimitive(block);
  return `${transforms[0]} ${transforms[1]} ${primitive}`;
}

function generatePrimitive(block: VisualBlock) {
  switch (block.kind) {
    case "cube":
      return `cube([${formatVector(block.size)}], center = ${block.center});`;
    case "sphere":
      return `sphere(r = ${formatNumber(block.radius)});`;
    case "cylinder":
      return `cylinder(h = ${formatNumber(block.height)}, r = ${formatNumber(block.radius)}, center = ${block.center});`;
  }
}

function formatVector(values: readonly number[]) {
  return values.map(formatNumber).join(", ");
}

function formatNumber(value: number) {
  return Number.isFinite(value) ? `${Math.round(value * 1000) / 1000}` : "0";
}

function indent(text: string) {
  return text
    .split("\n")
    .map((line) => `  ${line}`)
    .join("\n");
}
